### PR TITLE
feat: placement other specialties

### PR DESCRIPTION
**Pull request by ReubenRobertsHEE**
To be followed by sync service PR to populate this new field.

TIS21-5742
TIS21-5743

### CODE REVIEW

**Review by EdwardBarclay — APPROVED** [review]
LGTM

**Review by Judge40 — COMMENTED** [review]
Is there any specific reason not to deserialize to a Collection<String> instead of leaving it as a delimited string?

**Comment by ReubenRobertsHEE** [comment]
> Is there any specific reason not to deserialize to a Collection instead of leaving it as a delimited string?

Yeah, I was wondering about that. I thought that the delimited string was what the ticket asked for, though I guess it's a bit ambiguous: maybe it's just the display that requires the delimited string.  If it should go to a collection, we should probably define what fields a 'PlacementSpecialty' (sub)object should have.

**Comment by ReubenRobertsHEE** [comment]
(Its probably worth the sync service doing this, rather than trying to deserialize when its pushed to trainee-details, since some specialties have the delimiting character (,) i.e. https://build.tis.nhs.uk/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjozNiwicXVlcnkiOnsic291cmNlLXRhYmxlIjoxNjk5LCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDI1OTUzLG51bGxdLCJDVVJSRU5UIl0sWyJjb250YWlucyIsWyJmaWVsZCIsMjU5NTUsbnVsbF0sIiwiLHsiY2FzZS1zZW5zaXRpdmUiOmZhbHNlfV1dfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUuY29sdW1uX3dpZHRocyI6W251bGwsbnVsbCxudWxsLDQ4Ml19LCJvcmlnaW5hbF9jYXJkX2lkIjpudWxsfQ==

**Review by Judge40 — APPROVED** [review]
Approving as-is, but I'd still like to see that field split if/when we better understand it and/or handle it in the sync service.

**Review by Judge40 — APPROVED** [review]

**Pull request merged**
